TOTAL_JOGADORES    = 2
PORTA_SERVIDOR     = 9000

JOGADA_PAPEL       = 0
JOGADA_TESOURA     = 1
JOGADA_PEDRA       = 2

MSG_ENTRAR_PARTIDA = 100
MSG_SAIR_PARTIDA   = 101

MSG_PARTIDA_LOTADA     = 200
MSG_ENTRADA_ACEITA     = 201
MSG_ENTRADA_NEGADA     = 202
MSG_ESPERANDO_JOGADOR  = 203
MSG_ENVIAR_JOGADA	   = 204
MSG_ESPERANDO_COMECAR  = 205
MSG_REQUISITAR_ENTRADA = 206
MSG_COMECAR_PARTIDA    = 207
MSG_REQUISITAR_JOGADA  = 208
MSG_PREPARADO		   = 209

ENDERECO_DESCONHECIDO = 300
ENDERECO_CONHECIDO    = 301

MSG_EMPATE  = 400
MSG_DERROTA = 401
MSG_VITORIA = 402

JOGADAS    = (JOGADA_PAPEL, JOGADA_PEDRA, JOGADA_TESOURA)
RESULTADOS = (MSG_EMPATE, MSG_DERROTA, MSG_VITORIA)
